# Generated by Django 6.0.1 on 2026-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('manufacturing_year', models.IntegerField()),
                ('fipe_price', models.FloatField()),
            ],
            options={
                'db_table': 'truck',
            },
        ),
    ]
